config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  root to: 'dogs#index'
  resources :dogs do
    resources :inquiry_records
  end
  resources :users
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user 
  has_many :inquiry_records
  has_many :inquiry_forms
  has_one_attached :image

  enum dog_gender: { オス:1, メス:2 }
  enum vaccine:    { 接種済:1, 未接種:2 }
  enum surgery:    { 手術済:1, 未手術:2 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :dog_age
  belongs_to :prefecture
  
  with_options presence: true do
    validates :image, :dog_gender, :vaccine, :surgery, presence: { message: 'を選択してください'} 
    validates :title, length: { maximum: 40 }
    validates :feature, :reason, length: { maximum: 1000 }
  end

  with_options presence: true, numericality: { other_than: 1, message: 'を選択してください' } do
    validates :prefecture_id, :dog_age_id
  end

  validates :remarks, length: { maximum: 1000 }
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :dog_find_params, only: [:show, :edit,:update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @dogs = Dog.all.order('id DESC')
    search_dogs
    search_prefecture_culumn
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    
  end

  def edit
    
  end

  def update
    if @dog.update(dog_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @dog.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private
  def dog_params
    params.require(:dog).permit(:image, :title, :dog_gender, :dog_age_id, :vaccine, :surgery, :prefecture_id, :feature, :reason, :remarks).merge(user_id: current_user.id)
  end

  def search_dogs
    @q = Dog.ransack(params[:q])
    @dogs = @q.result(distinct: true)
  end

  def search_prefecture_culumn
    @prefecture = Prefecture.where.not(id: 1)
  end

  def dog_find_params
    @dog = Dog.find(params[:id])
  end

  def correct_user
    redirect_to root_path unless current_user.id == @dog.user.id
  end

end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/edit.html.erb
<%= render 'shared/header' %>

<%= form_with model: @dog, url: dog_path(@dog.id) ,class: 'registration-main', local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'> 
        わんちゃんの情報編集
      </h1>
    </div>

    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">画像</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:image) %>
          <%= @dog.errors.full_messages_for(:image).first %>
        <% end %>
        </p>
      </div>
      <div class="image-upload">
        <%= f.file_field :image, id: "dog-image" %>
      </div>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">掲載タイトル</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:title) %>
          <%= @dog.errors.full_messages_for(:title).first %>
        <% end %>
        </p>
      </div>
      <%= f.text_field :title, class: "input-default", id: "title", placeholder: "40文字以内", maxlength: "40" %>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">性別</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:dog_gender) %>
          <%= @dog.errors.full_messages_for(:dog_gender).first %>
        <% end %>
        </p>
      </div>
      <div class='radio-inline-box'>
        <div class='radio-inline'>
          <%= f.radio_button :dog_gender, :オス, class: "dog-radio-btn" %>
          <%= f.label :オス %>
        </div>
        <div class='radio-inline'>
          <%= f.radio_button :dog_gender, :メス, class: "dog-radio-btn" %>
          <%= f.label :メス %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">年齢</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
          <% if @dog.errors.include?(:dog_age_id) %>
            <%= @dog.errors.full_messages_for(:dog_age_id).first %>
          <% end %>
        </p>
      </div>
      <%= f.collection_select(:dog_age_id, DogAge.all, :id, :name, {}, {class:"select-box", id:"dog-age"}) %>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">ワクチン</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:vaccine) %>
          <%= @dog.errors.full_messages_for(:vaccine).first %>
        <% end %>
        </p>
      </div>
      <div class='radio-inline-box'>
        <div class='radio-inline'>
          <%= f.radio_button :vaccine, :接種済, class: "dog-radio-btn" %>
          <%= f.label :接種済 %>
        </div>
        <div class='radio-inline'>
          <%= f.radio_button :vaccine, :未接種, class: "dog-radio-btn" %>
          <%= f.label :未接種 %>
        </div>
      </div>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">去勢手術</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:surgery) %>
          <%= @dog.errors.full_messages_for(:surgery).first %>
        <% end %>
        </p>
      </div>
      <div class='radio-inline-box'>
        <div class='radio-inline'>
          <%= f.radio_button :surgery, :手術済, class: "dog-radio-btn" %>
          <%= f.label :手術済 %>
        </div>
        <div class='radio-inline'>
          <%= f.radio_button :surgery, :未手術, class: "dog-radio-btn" %>
          <%= f.label :未手術 %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">動物のいる地域</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
          <% if @dog.errors.include?(:prefecture_id) %>
            <%= @dog.errors.full_messages_for(:prefecture_id).first %>
          <% end %>
        </p>
      </div>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">特徴</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:feature) %>
          <%= @dog.errors.full_messages_for(:feature).first %>
        <% end %>
        </p>
      </div>
      <%= f.text_area :feature, class: "input-default-textarea", id: "feature", placeholder: "1000文字以内", maxlength: "1000" %>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">募集理由</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:reason) %>
          <%= @dog.errors.full_messages_for(:reason).first %>
        <% end %>
        </p>
      </div>
      <%= f.text_area :reason, class: "input-default-textarea", id: "reason", placeholder: "1000文字以内", maxlength: "1000" %>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">備考・その他</label>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:remarks) %>
          <%= @dog.errors.full_messages_for(:remarks).first %>
        <% end %>
        </p>
      </div>
      <%= f.text_area :remarks, class: "input-default-textarea", id: "remarks", placeholder: "1000文字以内", maxlength: "1000" %>
    </div>

      <div class='register-btn'>
        <%= f.submit "更新する", class: "register-red-btn"%>
      </div>
  </div>
<% end %>

<%= render 'shared/footer'%>

app/views/dogs/index.html.erb
<%= render 'shared/header'%>

<div class='main-container'>
  <div class='main-background-image'>
    <div class="dog-title">
      <h2 class="dog-title-text">
          里親募集情報
      </h2>
    </div>
    <div class="search-container">
      <%= search_form_for @q do |f| %>
          <%= f.label :title, "キーワード" %>
          <%= f.search_field :title_cont, class: "search-keywords" %>
          <%= f.label :prefecture, "募集対象地域"%>
          <%= f.collection_select :prefecture_id_eq, @prefecture, :id, :name, include_blank: '---', class: "search-prefecture" %>
          <%= f.submit "検索" %>
      <% end %>
    </div>
    <div class="dog-contents">
      <ul class="dog-lists">
        <% @dogs.each do |dog| %>
          <li class="list">
            <%= link_to dog_path(dog.id), class: "dog-info" do %>
            <h3 class="dog-list-title">
              <%= dog.title %>
            </h3>
            <div class="dog-img-content">
              <%= image_tag dog.image.variant(resize: '300x300'), class: "dog-img" %>
            </div>
            <p class="dog-gender">
              <%= dog.dog_gender %>
            </p>
            <p class="dog-prefecture">
              <%= dog.prefecture.name %>
            </p>
            <p class="date-update">
              登録:
              <%= l dog.created_at, format: :short %>
            </p>
            <p class="date-update">
              更新:
              <%= l dog.updated_at, format: :short %>
            </p>
            <p>
              問い合わせ数:<%= dog.inquiry_records.length %>
            </p>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%= render 'shared/footer'%>

app/views/dogs/new.html.erb
<%= render 'shared/header' %>

<%= form_with model: @dog, url: dogs_path ,class: 'registration-main', local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'> 
        わんちゃんの情報入力
      </h1>
    </div>

    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">画像</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:image) %>
          <%= @dog.errors.full_messages_for(:image).first %>
        <% end %>
        </p>
      </div>
      <div class="image-upload">
        <%= f.file_field :image, id: "dog-image" %>
      </div>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">掲載タイトル</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:title) %>
          <%= @dog.errors.full_messages_for(:title).first %>
        <% end %>
        </p>
      </div>
      <%= f.text_field :title, class: "input-default", id: "title", placeholder: "40文字以内", maxlength: "40" %>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">性別</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:dog_gender) %>
          <%= @dog.errors.full_messages_for(:dog_gender).first %>
        <% end %>
        </p>
      </div>
      <div class='radio-inline-box'>
        <div class='radio-inline'>
          <%= f.radio_button :dog_gender, :オス, class: "dog-radio-btn" %>
          <%= f.label :オス %>
        </div>
        <div class='radio-inline'>
          <%= f.radio_button :dog_gender, :メス, class: "dog-radio-btn" %>
          <%= f.label :メス %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">年齢</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
          <% if @dog.errors.include?(:dog_age_id) %>
            <%= @dog.errors.full_messages_for(:dog_age_id).first %>
          <% end %>
        </p>
      </div>
      <%= f.collection_select(:dog_age_id, DogAge.all, :id, :name, {}, {class:"select-box", id:"dog-age"}) %>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">ワクチン</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:vaccine) %>
          <%= @dog.errors.full_messages_for(:vaccine).first %>
        <% end %>
        </p>
      </div>
      <div class='radio-inline-box'>
        <div class='radio-inline'>
          <%= f.radio_button :vaccine, :接種済, class: "dog-radio-btn" %>
          <%= f.label :接種済 %>
        </div>
        <div class='radio-inline'>
          <%= f.radio_button :vaccine, :未接種, class: "dog-radio-btn" %>
          <%= f.label :未接種 %>
        </div>
      </div>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">去勢手術</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:surgery) %>
          <%= @dog.errors.full_messages_for(:surgery).first %>
        <% end %>
        </p>
      </div>
      <div class='radio-inline-box'>
        <div class='radio-inline'>
          <%= f.radio_button :surgery, :手術済, class: "dog-radio-btn" %>
          <%= f.label :手術済 %>
        </div>
        <div class='radio-inline'>
          <%= f.radio_button :surgery, :未手術, class: "dog-radio-btn" %>
          <%= f.label :未手術 %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">動物のいる地域</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
          <% if @dog.errors.include?(:prefecture_id) %>
            <%= @dog.errors.full_messages_for(:prefecture_id).first %>
          <% end %>
        </p>
      </div>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">特徴</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:feature) %>
          <%= @dog.errors.full_messages_for(:feature).first %>
        <% end %>
        </p>
      </div>
      <%= f.text_area :feature, class: "input-default-textarea", id: "feature", placeholder: "1000文字以内", maxlength: "1000" %>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">募集理由</label>
        <span class="indispensable">必須</span>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:reason) %>
          <%= @dog.errors.full_messages_for(:reason).first %>
        <% end %>
        </p>
      </div>
      <%= f.text_area :reason, class: "input-default-textarea", id: "reason", placeholder: "1000文字以内", maxlength: "1000" %>
    </div>
    <div class='form-group'>
      <div class='form-text-wrap'>
        <label class="form-text">備考・その他</label>
        <p class='error-text-message'>
        <% if @dog.errors.include?(:remarks) %>
          <%= @dog.errors.full_messages_for(:remarks).first %>
        <% end %>
        </p>
      </div>
      <%= f.text_area :remarks, class: "input-default-textarea", id: "remarks", placeholder: "1000文字以内", maxlength: "1000" %>
    </div>

      <div class='register-btn'>
        <%= f.submit "掲載する", class: "register-red-btn"%>
      </div>
  </div>
<% end %>

<%= render 'shared/footer'%>

app/views/dogs/show.html.erb
<%= render 'shared/header'%>
<div class='mypage-main'>
  <div class='mypage-box'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        <%= @dog.title %>
      </h1>
    </div>
    
    <div class='dogpage-img-content'>
      <%= image_tag @dog.image.variant(resize: '300x300'), class: "dogpage-box-img" %>
    </div>
    <table class="dog-detail-table">
      <tbody>
        <tr>
          <th class="dogpage-detail">掲載者</th>
          <td class="dogpage-value"><%= @dog.user.nickname %></td>
          <th class="dogpage-detail">動物がいる地域</th>
          <td class="dogpage-value"><%= @dog.prefecture.name %></td>
        </tr>
        <tr>
          <th class="dogpage-detail">年齢</th>
          <td class="dogpage-value"><%= @dog.dog_age.name %></td>
          <th class="dogpage-detail">性別</th>
          <td class="dogpage-value"><%= @dog.dog_gender %></td>
        </tr>
        <tr>
          <th class="dogpage-detail">ワクチン</th>
          <td class="dogpage-value"><%= @dog.vaccine %></td>
          <th class="dogpage-detail">去勢手術</th>
          <td class="dogpage-value"><%= @dog.surgery %></td>
        </tr>
        <tr>
          <th class="dogpage-detail" colspan="1">特徴</th>
          <td class="dogpage-value" colspan="3"><%= @dog.feature %></td>
        </tr>
        <tr>
          <th class="dogpage-detail" colspan="1">募集理由</th>
          <td class="dogpage-value" colspan="3"><%= @dog.reason %></td>
        </tr>
        <tr>
          <th class="dogpage-detail" colspan="1">備考・その他</th>
          <td class="dogpage-value" colspan="3"><%= @dog.remarks %></td>
        </tr>
      </tbody>
    </table>
    <div class="mypage-btn">
      <% if user_signed_in? %>
        <% if current_user.id == @dog.user.id%>
          <%= link_to '編集', edit_dog_path(@dog.id), class: "mypage-red-btn" %>
          <%= link_to '削除', dog_path(@dog.id), method: :delete, data:{ confirm: "本当に削除しますか？"}, class: "mypage-red-btn" %>
          <% else %>
          <%= link_to '応募する', new_dog_inquiry_record_path(@dog.id), class: "mypage-green-btn" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<%= render 'shared/footer'%>